"""updated game table

Revision ID: 2fcbbead3212
Revises: b9f27b7a3c01
Create Date: 2025-08-24 16:48:20.969039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcbbead3212'
down_revision: Union[str, Sequence[str], None] = 'b9f27b7a3c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_white_turn', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_white_turn')
    # ### end Alembic commands ###
